In [ ]:
import pandas as pd;
import os

import pandas as pd

bios = pd.read_csv(r"C:\Users\Prakhar\Downloads\bios.csv")
bios.loc[1,["born_country"]]="india"
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,india,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [ ]:
bios.sort_values(["height_cm","weight_kg"], ascending=[0,1])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

filtering data

In [ ]:

# bios.loc[(bios["height_cm"]>215) & (bios["born_country"]=="USA")]
# MT 2
# bios[bios["name"].str.contains("keith")]
# mt3
bios.query('born_country=="USA" and born_city=="Burlingame"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
2719,2731,Diana Gee,1968-12-21,Burlingame,California,USA,United States,162.0,45.0,NaN
40145,40453,Catriona Fallon,1970-08-08,Burlingame,California,USA,United States,185.0,77.0,NaN
77768,78359,Ben Eastman,1911-07-09,Burlingame,California,USA,United States,185.0,70.0,2002-10-06
87182,87878,Duncan Kennedy,1967-12-20,Burlingame,California,USA,United States,180.0,77.0,NaN
107963,109104,Chloe Kloezeman,1986-05-29,Burlingame,California,USA,Greece,167.0,61.0,NaN

ADDING/ REMOVING COLUMNS

In [ ]:
import pandas as pd
coffee=pd.read_csv(r"C:\Users\Prakhar\Downloads\coffee.csv")
# coffee["price"]=4.99

# to be more specific
import numpy as np
coffee["price"]=np.where(coffee["Coffee Type"]=="Latte",3.99,6)
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   6.00
1     Monday       Latte          15   3.99
2    Tuesday    Espresso          30   6.00
3    Tuesday       Latte          20   3.99
4  Wednesday    Espresso          35   6.00

In [12]:
# to remove a row or a column 
# coffee.drop(0)
coffee.drop(columns=["price"])
# to rename a column
coffee.rename(columns={'price':'new_price'})

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       6.00
1      Monday       Latte          15       3.99
2     Tuesday    Espresso          30       6.00
3     Tuesday       Latte          20       3.99
4   Wednesday    Espresso          35       6.00
5   Wednesday       Latte          25       3.99
6    Thursday    Espresso          40       6.00
7    Thursday       Latte          30       3.99
8      Friday    Espresso          45       6.00
9      Friday       Latte          35       3.99
10   Saturday    Espresso          45       6.00
11   Saturday       Latte          35       3.99
12     Sunday    Espresso          45       6.00
13     Sunday       Latte          35       3.99

to convert a new data set into csv file

In [ ]:
coffee_new=coffee.copy()
coffee_new.to_csv('coffee_new.csv', index=False)

.apply()

In [23]:
import pandas as pd

bios = pd.read_csv(r"C:\Users\Prakhar\Downloads\bios.csv")
bios["height_category"]=bios["height_cm"].apply(lambda x:'short' if x<165 else('average' if x<185 else 'tall'))
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,tall